apiVersion: v1
kind: Service
metadata:
  name: lanchonete-svc
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: lanchonete-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP